name: Chips
options:
  bundleIdPrefix: com.chips
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    # Enable modules for C dependencies (cmark-gfm needs this)
    CLANG_ENABLE_MODULES: YES
    # Fix for cmark-gfm module compatibility with Xcode 15+ (macOS only)
    GCC_PREPROCESSOR_DEFINITIONS: "$(inherited) _DARWIN_C_SOURCE=1"
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"

targets:
  # iOS App Target
  Chips-iOS:
    type: application
    platform: iOS
    sources:
      - path: Chips
        excludes:
          - "**/*.xcassets"
      - path: Chips/Resources/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chips.app
        INFOPLIST_FILE: Chips/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        PRODUCT_NAME: Chips
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Chips/Resources/Chips.entitlements
        DEVELOPMENT_TEAM: ""
        TARGETED_DEVICE_FAMILY: "1,2"
        # Fix for cmark-gfm building for iOS Simulator
        ONLY_ACTIVE_ARCH: YES
        SUPPORTED_PLATFORMS: "iphonesimulator iphoneos"
        # Prevent macOS SDK from being used when building for iOS
        SUPPORTS_MACCATALYST: NO
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
    dependencies:
      - package: swift-markdown
        product: Markdown
      - package: Yams
      - target: ChipsShare
        embed: true

  # macOS App Target
  Chips-macOS:
    type: application
    platform: macOS
    sources:
      - path: Chips
        excludes:
          - "**/*.xcassets"
      - path: Chips/Resources/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chips.app
        INFOPLIST_FILE: Chips/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        PRODUCT_NAME: Chips
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Chips/Resources/Chips.entitlements
        # Allow building without a development team for local development
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        # Fix for cmark-gfm module compatibility with Xcode 15+ (macOS only)
        OTHER_CFLAGS: "$(inherited) -fmodule-map-file-home-is-cwd"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          CODE_SIGNING_REQUIRED: YES
          CODE_SIGNING_ALLOWED: YES
    dependencies:
      - package: swift-markdown
        product: Markdown
      - package: Yams

  # iOS Unit Tests
  ChipsTests-iOS:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ChipsTests
    dependencies:
      - target: Chips-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chips.app.tests
        INFOPLIST_FILE: ChipsTests/Info.plist
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Chips.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Chips"
        BUNDLE_LOADER: "$(TEST_HOST)"

  # macOS Unit Tests
  ChipsTests-macOS:
    type: bundle.unit-test
    platform: macOS
    sources:
      - ChipsTests
    dependencies:
      - target: Chips-macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chips.app.tests
        INFOPLIST_FILE: ChipsTests/Info.plist
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Chips.app/Contents/MacOS/Chips"
        BUNDLE_LOADER: "$(TEST_HOST)"

  # iOS UI Tests
  ChipsUITests-iOS:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - ChipsUITests
    dependencies:
      - target: Chips-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chips.app.uitests
        INFOPLIST_FILE: ChipsUITests/Info.plist
        TEST_TARGET_NAME: Chips-iOS

  # macOS UI Tests
  ChipsUITests-macOS:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - ChipsUITests
    dependencies:
      - target: Chips-macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chips.app.uitests
        INFOPLIST_FILE: ChipsUITests/Info.plist
        TEST_TARGET_NAME: Chips-macOS

  # Share Extension
  ChipsShare:
    type: app-extension
    platform: iOS
    sources:
      - ChipsShare
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chips.app.share
        INFOPLIST_FILE: ChipsShare/Info.plist
        PRODUCT_NAME: ChipsShare
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_ENTITLEMENTS: ChipsShare/ChipsShare.entitlements
        DEVELOPMENT_TEAM: ""
        SKIP_INSTALL: YES
    entitlements:
      path: ChipsShare/ChipsShare.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.chips.app

packages:
  swift-markdown:
    url: https://github.com/apple/swift-markdown
    from: "0.7.3"
  Yams:
    url: https://github.com/jpsim/Yams
    exactVersion: "6.0.2"

schemes:
  Chips-iOS:
    build:
      targets:
        Chips-iOS: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - ChipsTests-iOS
        - ChipsUITests-iOS
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  Chips-macOS:
    build:
      targets:
        Chips-macOS: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - ChipsTests-macOS
        - ChipsUITests-macOS
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
